# 最小構成テスト
# command : ansible-playbook git-install-test.yml


- name: Test git install
  hosts: webserver
  tasks:
    - file: path=/vagrant/rails_project state=directory owner=root group=root mode=0755
    - git:
        repo: https://github.com/qeema/ansible.git
        dest: /vagrant/rails_project
        version: develop 
        clone: yes
        update: yes
