- name: Configure rails webserver
  hosts: webserver
  become: True
  tasks:
    - name: install git
      yum : name=git

    - name: install tmux
      yum : name=tmux

    - name : set locale lang
      shell: |
        localectl set-locale LANG=ja_JP.utf8
        source /etc/locale.conf
    
    - name : set timezone
      shell: timedatectl set-timezone Asia/Tokyo

    - yum: name={{item}} state=latest
      with_items:
        - wget
        - gcc
        - gcc-c++
        - make
        - openssl-devel
        - zlib-devel
        - readline-devel
        - sqlite-devel

    # install ruby
    - get_url: >
        url=http://core.ring.gr.jp/pub/lang/ruby/ruby-2.3-stable.tar.gz 
        dest=/usr/local/src/
    - unarchive: >
        src=/usr/local/src/ruby-2.3-stable.tar.gz dest=/usr/local/src/
        creates=/usr/local/src/ruby-2.3-stable
    - shell: >
        ./configure --with-opt-dir=/usr/local --enable-shared --enable-option-checking &&
        make &&
        make test &&
        make install
        chdir=/usr/local/src/ruby-2.3.1
        creates=/usr/local/bin/ruby

    # install rails
    - name: Install rails
      gem:
        name      : rails
        version   : 4.2.7
        state     : present
        executable: /usr/local/bin/gem

