- name: Configure rails webserver
  hosts: webserver
  become: True

  vars:
    - project_dir:       "/vagrant/rails_projects"
    - project_repo:      "https://github.com/qeema/rails_projects.git"
    - mysql_root_passwd: "g34q23t9u@gwea"
    - rails_production_pass: "testteak389@5k93lpdfae"

  tasks:

    - name : set locale lang
      shell: |
        localectl set-locale LANG=ja_JP.utf8
        source /etc/locale.conf
    
    - name : set timezone
      shell: timedatectl set-timezone Asia/Tokyo

    - name: install iroiro 
      yum : name={{item}} state=latest
      with_items:
        - wget
        - unzip
        - gcc
        - gcc-c++
        - make
        - openssl-devel
        - zlib-devel
        - readline-devel
        - sqlite-devel
        - ruby-devel
        - git
        - tmux
        - nodejs
        - zsh

    - name : set default shell
      shell: chsh -s '/bin/zsh' root

    - name : add mysql repo
      shell: |
            rpm -ih http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
            creates=/etc/yum.repos.d/mysql-community.repo

    - name: ins mysql
      yum : name={{item}} state=present enablerepo=mysql56-community
      with_items:
        - mysql-community-server
        - mysql-community-client
        - mysql-community-common
        - mysql-community-libs
        - mysql-community-libs-compat
        - mysql-devel

    - name   : start server
      service: name=mysqld state=started enabled=yes

    - name: install mysql-python
      yum: name=MySQL-python state=present

    - name    : first root password
      shell   : cat /var/log/mysqld.log | grep password | awk '{ print $NF }' | head -n 1
      register: mysql_passwd
 
#TODO cui security error. have to improve  
#    - name: check mysql root password
#      command  : mysqlshow -uroot -p'{{ mysql_passwd.stdout }}'
#      register : root_check
#      ignore_errors: True

#    - name: set mysql root password
#      command: mysql --connect-expired-password -uroot -p'{{ mysql_passwd.stdout }}' -e "set password for root@'localhost' = PASSWORD('{{ mysql_root_passwd }}')"
#      when: root_check.stderr.find('denied') == -1

    # install nginx
    - name : add nginx repo
      shell: |
            rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
            #creates= /etc/yum.repos.d/nginx.repo
  
    - name: install nginx
      yum : name=nginx state=latest

    # install ruby
    - name: get ruby url
      get_url: >
        url=http://core.ring.gr.jp/pub/lang/ruby/ruby-2.3-stable.tar.gz 
        dest=/usr/local/src/

    - command: tar zxvf /usr/local/src/ruby-2.3-stable.tar.gz chdir=/usr/local/src

    - shell: >
        ./configure --with-opt-dir=/usr/local --enable-shared --enable-option-checking &&
        make &&
        make test &&
        make install
        chdir=/usr/local/src/ruby-2.3.1
        creates=/usr/local/bin/ruby

    # install rails
    - name: Install rails
      gem :
        name        : rails
        version     : 4.2.7
        state       : present
        executable  : /usr/local/bin/gem
        user_install: no

    - name: Install coffee-rails
      gem:
        name        : coffee-rails
        version     : 4.1.0
        state       : present
        executable  : /usr/local/bin/gem
        user_install: no

    - name: Install web-console
      gem:
        name        : web-console
        version     : 2.0
        state       : present
        executable  : /usr/local/bin/gem
        user_install: no

    - name: install gems
      gem : name={{item}} state=latest user_install=no executable=/usr/local/bin/gem
      with_items: 
        - sqlite3
        - bundler
        - sass-rails
        - uglifier
        - jquery-rails
        - turbolinks
        - sdoc
        - unicorn
        - byebug
        - spring
        - jbuilder
        - therubyracer
        - pry-rails
        - pry-byebug
        - hirb
        - hirb-unicode
        - mysql2

    # set project app
    - file: path="{{ project_dir }}" state=directory owner=root group=root mode=0755
    - git :
        repo    : "{{ project_repo }}"
        dest    : "{{ project_dir }}"
        version : develop
        clone   : yes
        update  : yes

